export const STAGE_ALIASES: Record<string, string> = {
  layer_silicon: 'layer_electronics',
  'layer-1': 'layer_electronics',
  silicon: 'layer_electronics',
  '1': 'layer_electronics',
  layer_isa: 'layer_coa',
  'layer-2': 'layer_coa',
  isa: 'layer_coa',
  microarchitecture: 'layer_coa',
  '2': 'layer_coa',
  layer_kernel: 'layer_os',
  'layer-3': 'layer_os',
  kernel: 'layer_os',
  os: 'layer_os',
  '3': 'layer_os',
  layer_compilation: 'layer_compilers',
  'layer-4': 'layer_compilers',
  compilation: 'layer_compilers',
  compiler: 'layer_compilers',
  '4': 'layer_compilers',
  layer_runtime: 'layer_compilers',
  'layer-5': 'layer_compilers',
  runtime: 'layer_compilers',
  '5': 'layer_compilers',
  layer_contracts: 'layer_oop',
  'layer-6': 'layer_oop',
  contracts: 'layer_oop',
  types: 'layer_oop',
  '6': 'layer_oop',
  layer_paradigms: 'layer_distributed',
  'layer-7': 'layer_distributed',
  paradigms: 'layer_distributed',
  '7': 'layer_distributed',
  layer_hci: 'layer_hci',
  'layer-8': 'layer_hci',
  hci: 'layer_hci',
  ergonomics: 'layer_hci',
  '8': 'layer_hci',
};

export const CLUSTER_TO_STAGE: Record<string, string> = {
  // Tower layer IDs:
  electronics: 'layer_electronics',
  logic: 'layer_logic',
  architecture: 'layer_coa',
  math: 'layer_math',
  theory: 'layer_toc',
  comp_core: 'layer_dsa',
  systems_foundation: 'layer_compilers',
  os: 'layer_os',
  networking: 'layer_cn',
  data: 'layer_dbms',
  programming: 'layer_oop',
  system_design: 'layer_distributed',
  swe: 'layer_swe',
  human: 'layer_hci',

  // Deep language cluster IDs:
  memory: 'layer_os',
  'memory-lifetime': 'layer_os',
  'compilation-linkage': 'layer_compilers',
  modules: 'layer_swe',
  metaprogramming: 'layer_compilers',
  dispatch: 'layer_oop',
  'effects-sequencing': 'layer_compilers',
  'error-signalling': 'layer_oop',
  'evaluation-order': 'layer_compilers',
  types: 'layer_oop',
  'abstraction-over-types': 'layer_oop',
  'mutability-aliasing': 'layer_oop',
  'identity-equality': 'layer_oop',
  paradigms: 'layer_oop',
  'data-modelling': 'layer_dbms',
  concurrency: 'layer_distributed',
  'syntactic-ergonomics': 'layer_hci',
};
