/**
 * 15-Minute Pre-Interview Cheat Sheet Generator (Amelia — Lead Dev)
 * Reads verified invariants and saved STAR stories from Cognitive DB,
 * producing a printable 1-page condensed Markdown summary.
 */

import { globalCognitiveDB, type PreInterviewCheatSheetRecord, type StarStoryRecord } from '../../storage/cognitiveDatabase';
import { globalKnowledgeEngine } from '../hybridKnowledgeEngine';

export class CheatSheetGenerator {
  /**
   * Generates a 1-page emergency pre-interview cheat sheet and saves it to DB
   */
  public static async generateAndSave({
    companyName,
    role
  }: {
    companyName: string;
    role: string;
  }): Promise<PreInterviewCheatSheetRecord> {
    const starStories = await globalCognitiveDB.getAll<StarStoryRecord>('star_stories');
    const topStories = starStories.slice(0, 3);

    // Retrieve Top System Invariants
    const searchResults = globalKnowledgeEngine.search(`${companyName} ${role} architecture distributed react19 v8`, 4);
    const invariants = searchResults.flatMap(r => r.doc.invariants).slice(0, 8);

    const markdownContent = `
# ⚡ 15-Minute Pre-Interview Emergency Cheat Sheet
**Target**: ${companyName} · **Role**: ${role} · **Generated**: ${new Date().toLocaleDateString()}

---

## 🏛️ 1. Core Architectural Invariants (Must Recite)
${invariants.map((inv, i) => `${i + 1}. **${inv}**`).join('\n')}

---

## 🎯 2. Top Quantified STAR Defense Stories
${topStories.length > 0
  ? topStories.map(s => `### 📌 ${s.title} (${s.category})
- **Situation & Task**: ${s.situation} ${s.task}
- **Action**: ${s.action}
- **Result & Metrics**: ${s.result}`).join('\n\n')
  : `### 📌 Distributed Rate Limiter & Concurrency Defense
- **Action**: Partitioned Redis keys with CRC16 slots, combined with in-memory Token Bucket sliding logs.
- **Result**: Reduced P99 latency by 45%, eliminated single-node master bottlenecks.`
}

---

## 🔬 3. Critical Mental Models
- **V8 Engine**: Monomorphic call-sites execute in 1–2 CPU cycles; avoid dynamic property deletion.
- **React 19**: \`useActionState\` manages transitions; \`useOptimistic\` applies rollback on rejection.
- **Distributed Consensus**: CRDT LWW-Element-Set requires Commutative, Associative, and Idempotent joins.

---
*Generated by PrepWizard Cognitive Agent Engine. Persisted in Cognitive DB.*
`.trim();

    const record: PreInterviewCheatSheetRecord = {
      id: `sheet-${companyName.toLowerCase().replace(/\s+/g, '-')}-${Date.now()}`,
      companyName,
      role,
      markdownContent,
      invariantsSummary: invariants,
      topStarStoryIds: topStories.map(s => s.id),
      createdAt: Date.now()
    };

    // Commit to Cognitive Database
    await globalCognitiveDB.put('cheat_sheets', record);
    return record;
  }
}
